### ISSUE TITLE
AttributeError: module 'caffe.proto.caffe_pb2' has no attribute 'ResizeParameter'

### ISSUE THREAD

**Issue by alanumer234** [lampsonSong/tinySSD#13]
I am getting this error when I run generate.py

Traceback (most recent call last):
  File "python_script/generate.py", line 229, in <module>
    write_net(train_proto, train_lmdb, deploy_proto, label_file)
  File "python_script/generate.py", line 214, in write_net
    f.write(str(generate_net(train_lmdb, label_file, "TRAIN", batch_size=64)))
  File "python_script/generate.py", line 87, in generate_net
    resize_param=dict(prob=1.0, resize_mode=caffe.params.Resize.WARP, height=300, width=300, 
  File "/usr/lib/python3/dist-packages/caffe/net_spec.py", line 224, in __getattr__
    return getattr(getattr(caffe_pb2, name + 'Parameter'), param_name)
AttributeError: module 'caffe.proto.caffe_pb2' has no attribute 'ResizeParameter'

Note: I am not sure if I installed caffe incorrectly. I am using caffe first time. I installed caffe on google colab with following command.
!apt install -y caffe-cuda

**Comment by ujsyehao** [comment]
@alanumer234 You should install Caffe from the source.
