### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by sbastani** [lampsonSong/tinySSD#7]
When I run generate.py, I get this error

Traceback (most recent call last):
  File "python_script/generate.py", line 229, in <module>
    write_net(train_proto, train_lmdb, deploy_proto, label_file)
  File "python_script/generate.py", line 214, in write_net
    f.write(str(generate_net(train_lmdb, label_file, "TRAIN", batch_size=64)))
  File "python_script/generate.py", line 87, in generate_net
    resize_param=dict(prob=1.0, resize_mode=caffe.params.Resize.WARP, height=300, width=300, 
  File "/home/saba/caffe/python/caffe/net_spec.py", line 224, in __getattr__
    return getattr(getattr(caffe_pb2, name + 'Parameter'), param_name)
AttributeError: 'module' object has no attribute 'ResizeParameter'

**Comment by lampsonSong** [comment]
@sbastani It is the same problem. Please check https://github.com/lampsonSong/tinySSD/issues/8
